api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false

experimental:
  localPlugins:
    example:
      moduleName: github.com/bluecatengineering/traefik-aws-plugin
