name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.github/workflows/release.yaml'
  pull_request:

jobs:

  build:
    name: build
    env:
      GO_VERSION: 1.21.3
      GOLANGCI_LINT_VERSION: v1.55.2
      CGO_ENABLED: 0
    runs-on: ubuntu-latest
    steps:

    # https://github.com/marketplace/actions/setup-go-environment
    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v3
      with:
        go-version: ^${{ env.GO_VERSION }}

    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up GOPATH
      run: go env -w GOPATH=${{ github.workspace }}/go

    - name: Check and get dependencies
      run: |
        go mod tidy
        git diff --exit-code go.mod
        go mod download
        go mod vendor

    # https://github.com/marketplace/actions/run-golangci-lint
    - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ env.GOLANGCI_LINT_VERSION }}
        args: "--help"

    - name: Lint, Test, Build
      run: make lint test build

    - name: Copy sources
      run: make copy_src
